package spot

import "testing"

func TestNewSpotIsHumanByDefault(t *testing.T) {
	dx := "W1ABC"
	de := "K1XYZ"
	freq := 14074.5
	mode := "FT8"
	s := NewSpot(dx, de, freq, mode)
	if !s.IsHuman {
		t.Fatalf("NewSpot should mark the spot as human-generated by default")
	}
}
